/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author hp
 */
public class Divisas extends javax.swing.JFrame {
    
    private String cadenaNumeros  = "" ;
    private double numero1,numero2;
    private boolean activado = true;
    private boolean punto = true;
    private String divisa1="";
    private String divisa2="";
    private double dinero,cambio;
    

    /**
     * Creates new form Divisas
     */
    public Divisas() {
        initComponents();
        this.setSize(431,600);
        this.setLocationRelativeTo(null);
    }
       private void CalcularCambio(){
        
       cadenaNumeros =etiquetaCambio.getText();
       dinero = Double.parseDouble(cadenaNumeros);
       cambioDivisa();
       dinero *= cambio;
       etiquetaCambio2.setText(String.format("%.2f",dinero));
    }

    private void cambioDivisa(){
        if(divisa1.equals(divisa2)){
            cambio = 1;
            
        }
        else if(divisa1.equals("Dolares")&& divisa2.equals("Euros")){
            cambio=0.85;
        }
        else if(divisa1.equals("Dolares")&& divisa2.equals("Pesos Colombianos")){
            cambio =3.842;
        }
        
        else if(divisa1.equals("Euros")&& divisa2.equals("Dolares")){
            cambio=1.18 ;
        }
        
        else if(divisa1.equals("Euros")&& divisa2.equals("Pesos Colombianos")){
            cambio=4.524;
        }
        
        else if(divisa1.equals("Pesos Colombianos")&& divisa2.equals("Dolares")){
            cambio=0.00026;
        }
        
        else if(divisa1.equals("Pesos Colombianos")&& divisa2.equals("Euros")){
            cambio=0.00022;
            }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton7 = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        etiquetaDivisa1 = new javax.swing.JLabel();
        comboEntrada = new javax.swing.JComboBox<>();
        etiquetaCambio2 = new javax.swing.JLabel();
        comboSalida = new javax.swing.JComboBox<>();
        botonClean = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonPunto = new javax.swing.JButton();
        etiquetaCambio = new javax.swing.JLabel();
        etiquetaDivisa2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu2 = new javax.swing.JMenu();
        itemCalculadora = new javax.swing.JMenuItem();
        itemConversor = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de Dinero");
        setFont(new java.awt.Font("Adobe Devanagari", 1, 12)); // NOI18N

        panel2.setLayout(new java.awt.GridBagLayout());

        etiquetaDivisa1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        etiquetaDivisa1.setText("$ ");
        etiquetaDivisa1.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 100, 20, 0);
        panel2.add(etiquetaDivisa1, gridBagConstraints);

        comboEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolares", "Euros", "Pesos Colombianos" }));
        comboEntrada.setMaximumSize(new java.awt.Dimension(327, 327));
        comboEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEntradaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        panel2.add(comboEntrada, gridBagConstraints);

        etiquetaCambio2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        etiquetaCambio2.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        panel2.add(etiquetaCambio2, gridBagConstraints);

        comboSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolares", "Euros", "Pesos Colombianos" }));
        comboSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSalidaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(40, 20, 40, 20);
        panel2.add(comboSalida, gridBagConstraints);

        botonClean.setText("C");
        botonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCleanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel2.add(botonClean, gridBagConstraints);

        botonBorrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonBorrar.setText("←");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel2.add(botonBorrar, gridBagConstraints);

        boton7.setText("7");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel2.add(boton7, gridBagConstraints);

        boton8.setText("8");
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel2.add(boton8, gridBagConstraints);

        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel2.add(boton9, gridBagConstraints);

        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel2.add(boton6, gridBagConstraints);

        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel2.add(boton5, gridBagConstraints);

        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel2.add(boton4, gridBagConstraints);

        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel2.add(boton1, gridBagConstraints);

        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel2.add(boton2, gridBagConstraints);

        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel2.add(boton3, gridBagConstraints);

        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel2.add(boton0, gridBagConstraints);

        botonPunto.setText(".");
        botonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel2.add(botonPunto, gridBagConstraints);

        etiquetaCambio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        etiquetaCambio.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel2.add(etiquetaCambio, gridBagConstraints);

        etiquetaDivisa2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        etiquetaDivisa2.setText("$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 100, 0, 0);
        panel2.add(etiquetaDivisa2, gridBagConstraints);

        menu2.setText("Usos");

        itemCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calculadora.png"))); // NOI18N
        itemCalculadora.setText("Calculadora Convencional");
        itemCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCalculadoraActionPerformed(evt);
            }
        });
        menu2.add(itemCalculadora);

        itemConversor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/convertidor.png"))); // NOI18N
        itemConversor.setText("Conversor de Dinero");
        menu2.add(itemConversor);

        itemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/X_opt.png"))); // NOI18N
        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        menu2.add(itemSalir);

        jMenuBar1.add(menu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCalculadoraActionPerformed
       Calculadora calcular = new Calculadora();
       calcular.setVisible(true);
       dispose();
    }//GEN-LAST:event_itemCalculadoraActionPerformed

    private void comboEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEntradaActionPerformed
        divisa1= (String ) comboEntrada.getSelectedItem();
        if(divisa1.equals("Dolares")){
            etiquetaDivisa1.setText("$");
        }
        else if(divisa1.equals("Euros")){
        etiquetaDivisa1.setText("€");
        
    }
        else if(divisa1.equals("Pesos Colombianos")){
            etiquetaDivisa1.setText("PE.");
        }
        
       CalcularCambio();
        
    }//GEN-LAST:event_comboEntradaActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
  
        
        if(etiquetaCambio.getText()== "0"){
            cadenaNumeros="1";
        }else{
            cadenaNumeros+= "1";
        }
     etiquetaCambio.setText(cadenaNumeros);
  CalcularCambio();
           
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
     
        if(etiquetaCambio.getText()== "0"){
            cadenaNumeros="5";
        }else{
            cadenaNumeros+= "5";
        }
     etiquetaCambio.setText(cadenaNumeros);
  CalcularCambio();
   
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
          
        if(etiquetaCambio.getText()== "0"){
            cadenaNumeros="3";
        }else{
            cadenaNumeros+= "3";
        }
     etiquetaCambio.setText(cadenaNumeros);
  CalcularCambio();   
 
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
   
        if(etiquetaCambio.getText()== "0"){
            cadenaNumeros="2";
        }else{
            cadenaNumeros+= "2";
        }
     etiquetaCambio.setText(cadenaNumeros);
  CalcularCambio();
    
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
   
        if(etiquetaCambio.getText()== "0"){
            cadenaNumeros="8";
        }else{
            cadenaNumeros+= "8";
        }
     etiquetaCambio.setText(cadenaNumeros);
  CalcularCambio();
    }//GEN-LAST:event_boton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
   
        if(etiquetaCambio.getText()== "0"){
            cadenaNumeros="9";
        }else{
            cadenaNumeros+= "9";
        }
     etiquetaCambio.setText(cadenaNumeros);
  CalcularCambio();
    }//GEN-LAST:event_boton9ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
     
        if(etiquetaCambio.getText()== "0"){
            cadenaNumeros="4";
        }else{
            cadenaNumeros+= "4";
        }
     etiquetaCambio.setText(cadenaNumeros);
  CalcularCambio(); 
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
    
        if(etiquetaCambio.getText()== "0"){
            cadenaNumeros="6";
        }else{
            cadenaNumeros+= "6";
        }
     etiquetaCambio.setText(cadenaNumeros);
  CalcularCambio(); 
    }//GEN-LAST:event_boton6ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
  
        if(etiquetaCambio.getText()== "0"){
            cadenaNumeros="7";
        }else{
            cadenaNumeros+= "7";
        }
     etiquetaCambio.setText(cadenaNumeros);
  CalcularCambio(); 
    }//GEN-LAST:event_boton7ActionPerformed

    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed
        if (punto==true){
             if (cadenaNumeros==""){
             
             cadenaNumeros="0.";
       
        }
        else {
        cadenaNumeros += ".";
       
        }
              etiquetaCambio.setText(cadenaNumeros);
        }
   
      punto = false;
    }//GEN-LAST:event_botonPuntoActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        int tamano = cadenaNumeros.length();
        if(tamano>0){
            if(tamano == 1 ){
                cadenaNumeros="0";
            }
            else{
                 cadenaNumeros= cadenaNumeros.substring(0,cadenaNumeros.length()-1);
            }
               
            }
            etiquetaCambio.setText(cadenaNumeros);
            CalcularCambio(); 
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCleanActionPerformed
        
      
      cadenaNumeros=" ";
       punto = true;
      etiquetaCambio.setText("0");
      etiquetaCambio2.setText("0");
     
    }//GEN-LAST:event_botonCleanActionPerformed

    private void comboSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSalidaActionPerformed
        divisa2= (String ) comboSalida.getSelectedItem();
        
        if(divisa2.equals("Dolares")){
            etiquetaDivisa2.setText("$");
           
        }
        else if(divisa2.equals("Euros")){
        etiquetaDivisa2.setText("€");
        
    }
        else if(divisa2.equals("Pesos Colombianos")){
            etiquetaDivisa2.setText("PE.");
        }      
        CalcularCambio();
    }//GEN-LAST:event_comboSalidaActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
  
 if(cadenaNumeros != ""){
     if(etiquetaCambio.getText() == "0"){
         cadenaNumeros="0";
     }
     else{
         cadenaNumeros+="0";
     }
     
     etiquetaCambio.setText(cadenaNumeros);
     CalcularCambio();
 }  
 
    }//GEN-LAST:event_boton0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        try {
            UIManager.setLookAndFeel("com.jtatto.plaf.texture.MintLookAndFeel  ");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            //Logger.getLogger(Divisas.class.getName()).log(Level.SEVERE, null, ex);
        }
        // Logger.getLogger(Divisas.class.getName()).log(Level.SEVERE, null, ex);
        // Logger.getLogger(Divisas.class.getName()).log(Level.SEVERE, null, ex);
        // Logger.getLogger(Divisas.class.getName()).log(Level.SEVERE, null, ex);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Divisas().setVisible(true);
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonClean;
    private javax.swing.JButton botonPunto;
    private javax.swing.JComboBox<String> comboEntrada;
    private javax.swing.JComboBox<String> comboSalida;
    private javax.swing.JLabel etiquetaCambio;
    private javax.swing.JLabel etiquetaCambio2;
    private javax.swing.JLabel etiquetaDivisa1;
    private javax.swing.JLabel etiquetaDivisa2;
    private javax.swing.JMenuItem itemCalculadora;
    private javax.swing.JMenuItem itemConversor;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JButton jButton7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu2;
    private javax.swing.JPanel panel2;
    // End of variables declaration//GEN-END:variables
}
